/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.reshopper.dfp;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import android.os.Bundle;
import android.location.Location;
import java.io.IOException;

import com.google.android.gms.ads.doubleclick.PublisherAdRequest;
import com.google.android.gms.ads.AdSize;

import com.google.android.gms.common.GooglePlayServicesNotAvailableException;
import com.google.android.gms.common.GooglePlayServicesRepairableException;
import com.google.android.gms.ads.identifier.AdvertisingIdClient;

@Kroll.module(name="ComReshopperDfp", id="com.reshopper.dfp")
public class ComReshopperDfpModule extends KrollModule
{

    // Standard Debugging variables
    private static final String LCAT = "[com.reshopper.dfp] module";
    private static final boolean DBG = TiConfig.LOGD;
    
    
    @Kroll.constant
    public static final String EMULATOR_ID = "[[[[[ -- PublisherAdRequest.DEVICE_ID_EMULATOR -- ]]]]]";
    
    public static String[] TEST_DEVICES = {};
    public static String ADUNIT_ID;
    public static String CONTENT_URL;
    
    public static Location LOCATION = null;
    
    public static Bundle CUSTOM_TARGETING = null;
    
    public static Boolean SUPPRESS_SCROLL = true;
    
    public static Integer ADHEIGHT = 0;
    public static Integer ADWIDTH = 0;
    
    public static AdSize[] AD_SIZES;
    
    
    
    // *
    public static String PROPERTY_COLOR_BG =     "adBackgroundColor";
    public static String PROPERTY_COLOR_BG_TOP = "backgroundTopColor";
    public static String PROPERTY_COLOR_BORDER = "borderColor";
    public static String PROPERTY_COLOR_TEXT =   "textColor";
    public static String PROPERTY_COLOR_LINK =   "linkColor";
    public static String PROPERTY_COLOR_URL =    "urlColor";

    
    private String advertisingId = "";
    private boolean adTrackingDisabled = false;
    
    
    // You can define constants with @Kroll.constant, for example:
    // @Kroll.constant public static final String EXTERNAL_NAME = value;
    
    public ComReshopperDfpModule()
    {
        super();
        
        /*
        Log.d (LCAT, "starting new thread to get advertising ID");
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    AdvertisingIdClient.Info adInfo = AdvertisingIdClient.getAdvertisingIdInfo(TiApplication.getInstance());
                    finished (adInfo);
                    return;
                }
                catch (IOException e) {
                    Log.w (LCAT, "call to getAdvertisingInfo() failed; could not make connection to google play services");
                }
                catch (IllegalStateException e) {
                    Log.w (LCAT, "call to getAdvertisingInfo() failed; method called on main thread");
                }
                catch (GooglePlayServicesNotAvailableException e) {
                    Log.w (LCAT, "call to getAdvertisingInfo() failed; google play services not available");
                }
                catch (GooglePlayServicesRepairableException e) {
                    Log.w (LCAT, "call to getAdvertisingInfo() failed; recoverable error connecting to google play services");
                }
                
                finished (null);
            }
        });
        t.start();
         */
        
        Log.d (LCAT, "module instantiated");
    }
    
  
}

